/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TesfaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BARTER_SHARE"
      | "BASE_RATE"
      | "BUYER_SHARE"
      | "DEMURRAGE_INTERVAL"
      | "INACTIVE_PERIOD"
      | "INACTIVE_THRESHOLD"
      | "MAX_SUPPLY"
      | "SELLER_SHARE"
      | "TAX_RATE"
      | "allowance"
      | "approve"
      | "authorizeBarterFacilitator"
      | "authorizeBusiness"
      | "authorizedBarterFacilitators"
      | "authorizedBusinesses"
      | "balanceOf"
      | "capReached"
      | "claimUBI"
      | "collectDemurrage"
      | "decimals"
      | "decreaseAllowance"
      | "increaseAllowance"
      | "isBusinessAccount"
      | "isPersonalAccount"
      | "isRegistered"
      | "lastActivity"
      | "lastDemurrageTime"
      | "name"
      | "pendingTSF"
      | "phoneToWallet"
      | "platformAdmin"
      | "recordBarter"
      | "recordPurchase"
      | "recoverInactive"
      | "register"
      | "revokeBarterFacilitator"
      | "revokeBusiness"
      | "symbol"
      | "totalRegistered"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "ubiPool"
      | "walletToPhone"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "BarterFacilitatorAuthorized"
      | "BarterFacilitatorRevoked"
      | "BusinessAccountCreated"
      | "BusinessAuthorized"
      | "BusinessRevoked"
      | "DemurrageCollected"
      | "InactiveRecovered"
      | "PendingTSFClaimed"
      | "PendingTSFCreated"
      | "PersonalAccountCreated"
      | "PhoneLinked"
      | "Registered"
      | "TSFMintedFromBarter"
      | "TSFMintedFromPurchase"
      | "TaxCollected"
      | "Transfer"
      | "UBIClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BARTER_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BASE_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BUYER_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INACTIVE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INACTIVE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELLER_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TAX_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeBarterFacilitator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeBusiness",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedBarterFacilitators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedBusinesses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "capReached",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimUBI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collectDemurrage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isBusinessAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPersonalAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastActivity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDemurrageTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingTSF",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "phoneToWallet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordBarter",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPurchase",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverInactive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "register", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "revokeBarterFacilitator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeBusiness",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ubiPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "walletToPhone",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BARTER_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BASE_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BUYER_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INACTIVE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INACTIVE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SELLER_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TAX_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeBarterFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeBusiness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedBarterFacilitators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedBusinesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "capReached", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimUBI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectDemurrage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBusinessAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPersonalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDemurrageTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingTSF", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "phoneToWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordBarter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverInactive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeBarterFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeBusiness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ubiPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletToPhone",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BarterFacilitatorAuthorizedEvent {
  export type InputTuple = [facilitator: AddressLike];
  export type OutputTuple = [facilitator: string];
  export interface OutputObject {
    facilitator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BarterFacilitatorRevokedEvent {
  export type InputTuple = [facilitator: AddressLike];
  export type OutputTuple = [facilitator: string];
  export interface OutputObject {
    facilitator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BusinessAccountCreatedEvent {
  export type InputTuple = [business: AddressLike];
  export type OutputTuple = [business: string];
  export interface OutputObject {
    business: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BusinessAuthorizedEvent {
  export type InputTuple = [business: AddressLike];
  export type OutputTuple = [business: string];
  export interface OutputObject {
    business: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BusinessRevokedEvent {
  export type InputTuple = [business: AddressLike];
  export type OutputTuple = [business: string];
  export interface OutputObject {
    business: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DemurrageCollectedEvent {
  export type InputTuple = [
    hunter: AddressLike,
    target: AddressLike,
    burned: BigNumberish,
    hunterReward: BigNumberish,
    toPool: BigNumberish
  ];
  export type OutputTuple = [
    hunter: string,
    target: string,
    burned: bigint,
    hunterReward: bigint,
    toPool: bigint
  ];
  export interface OutputObject {
    hunter: string;
    target: string;
    burned: bigint;
    hunterReward: bigint;
    toPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InactiveRecoveredEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingTSFClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    phoneHash: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, phoneHash: string, amount: bigint];
  export interface OutputObject {
    user: string;
    phoneHash: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingTSFCreatedEvent {
  export type InputTuple = [phoneHash: BytesLike, amount: BigNumberish];
  export type OutputTuple = [phoneHash: string, amount: bigint];
  export interface OutputObject {
    phoneHash: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PersonalAccountCreatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhoneLinkedEvent {
  export type InputTuple = [user: AddressLike, phoneHash: BytesLike];
  export type OutputTuple = [user: string, phoneHash: string];
  export interface OutputObject {
    user: string;
    phoneHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisteredEvent {
  export type InputTuple = [user: AddressLike, phoneHash: BytesLike];
  export type OutputTuple = [user: string, phoneHash: string];
  export interface OutputObject {
    user: string;
    phoneHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TSFMintedFromBarterEvent {
  export type InputTuple = [
    partyA: BytesLike,
    partyB: BytesLike,
    amountEach: BigNumberish
  ];
  export type OutputTuple = [
    partyA: string,
    partyB: string,
    amountEach: bigint
  ];
  export interface OutputObject {
    partyA: string;
    partyB: string;
    amountEach: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TSFMintedFromPurchaseEvent {
  export type InputTuple = [
    buyerPhone: BytesLike,
    business: AddressLike,
    buyerAmount: BigNumberish,
    sellerAmount: BigNumberish
  ];
  export type OutputTuple = [
    buyerPhone: string,
    business: string,
    buyerAmount: bigint,
    sellerAmount: bigint
  ];
  export interface OutputObject {
    buyerPhone: string;
    business: string;
    buyerAmount: bigint;
    sellerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaxCollectedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UBIClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tesfa extends BaseContract {
  connect(runner?: ContractRunner | null): Tesfa;
  waitForDeployment(): Promise<this>;

  interface: TesfaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BARTER_SHARE: TypedContractMethod<[], [bigint], "view">;

  BASE_RATE: TypedContractMethod<[], [bigint], "view">;

  BUYER_SHARE: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  INACTIVE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  INACTIVE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  SELLER_SHARE: TypedContractMethod<[], [bigint], "view">;

  TAX_RATE: TypedContractMethod<[], [bigint], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  authorizeBarterFacilitator: TypedContractMethod<
    [facilitator: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizeBusiness: TypedContractMethod<
    [business: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedBarterFacilitators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  authorizedBusinesses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  capReached: TypedContractMethod<[], [boolean], "view">;

  claimUBI: TypedContractMethod<[], [void], "nonpayable">;

  collectDemurrage: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  decreaseAllowance: TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  increaseAllowance: TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  isBusinessAccount: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isPersonalAccount: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastActivity: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lastDemurrageTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  pendingTSF: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  phoneToWallet: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  platformAdmin: TypedContractMethod<[], [string], "view">;

  recordBarter: TypedContractMethod<
    [partyAPhone: BytesLike, partyBPhone: BytesLike, valueILS: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordPurchase: TypedContractMethod<
    [buyerPhoneHash: BytesLike, amountILS: BigNumberish],
    [void],
    "nonpayable"
  >;

  recoverInactive: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  register: TypedContractMethod<[phoneHash: BytesLike], [void], "nonpayable">;

  revokeBarterFacilitator: TypedContractMethod<
    [facilitator: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeBusiness: TypedContractMethod<
    [business: AddressLike],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalRegistered: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  ubiPool: TypedContractMethod<[], [bigint], "view">;

  walletToPhone: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BARTER_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUYER_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INACTIVE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INACTIVE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELLER_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TAX_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeBarterFacilitator"
  ): TypedContractMethod<[facilitator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizeBusiness"
  ): TypedContractMethod<[business: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedBarterFacilitators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizedBusinesses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "capReached"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimUBI"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectDemurrage"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBusinessAccount"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPersonalAccount"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastActivity"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastDemurrageTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingTSF"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "phoneToWallet"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "platformAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordBarter"
  ): TypedContractMethod<
    [partyAPhone: BytesLike, partyBPhone: BytesLike, valueILS: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPurchase"
  ): TypedContractMethod<
    [buyerPhoneHash: BytesLike, amountILS: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoverInactive"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[phoneHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeBarterFacilitator"
  ): TypedContractMethod<[facilitator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeBusiness"
  ): TypedContractMethod<[business: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalRegistered"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ubiPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "walletToPhone"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "BarterFacilitatorAuthorized"
  ): TypedContractEvent<
    BarterFacilitatorAuthorizedEvent.InputTuple,
    BarterFacilitatorAuthorizedEvent.OutputTuple,
    BarterFacilitatorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "BarterFacilitatorRevoked"
  ): TypedContractEvent<
    BarterFacilitatorRevokedEvent.InputTuple,
    BarterFacilitatorRevokedEvent.OutputTuple,
    BarterFacilitatorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "BusinessAccountCreated"
  ): TypedContractEvent<
    BusinessAccountCreatedEvent.InputTuple,
    BusinessAccountCreatedEvent.OutputTuple,
    BusinessAccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BusinessAuthorized"
  ): TypedContractEvent<
    BusinessAuthorizedEvent.InputTuple,
    BusinessAuthorizedEvent.OutputTuple,
    BusinessAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "BusinessRevoked"
  ): TypedContractEvent<
    BusinessRevokedEvent.InputTuple,
    BusinessRevokedEvent.OutputTuple,
    BusinessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DemurrageCollected"
  ): TypedContractEvent<
    DemurrageCollectedEvent.InputTuple,
    DemurrageCollectedEvent.OutputTuple,
    DemurrageCollectedEvent.OutputObject
  >;
  getEvent(
    key: "InactiveRecovered"
  ): TypedContractEvent<
    InactiveRecoveredEvent.InputTuple,
    InactiveRecoveredEvent.OutputTuple,
    InactiveRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "PendingTSFClaimed"
  ): TypedContractEvent<
    PendingTSFClaimedEvent.InputTuple,
    PendingTSFClaimedEvent.OutputTuple,
    PendingTSFClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PendingTSFCreated"
  ): TypedContractEvent<
    PendingTSFCreatedEvent.InputTuple,
    PendingTSFCreatedEvent.OutputTuple,
    PendingTSFCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PersonalAccountCreated"
  ): TypedContractEvent<
    PersonalAccountCreatedEvent.InputTuple,
    PersonalAccountCreatedEvent.OutputTuple,
    PersonalAccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PhoneLinked"
  ): TypedContractEvent<
    PhoneLinkedEvent.InputTuple,
    PhoneLinkedEvent.OutputTuple,
    PhoneLinkedEvent.OutputObject
  >;
  getEvent(
    key: "Registered"
  ): TypedContractEvent<
    RegisteredEvent.InputTuple,
    RegisteredEvent.OutputTuple,
    RegisteredEvent.OutputObject
  >;
  getEvent(
    key: "TSFMintedFromBarter"
  ): TypedContractEvent<
    TSFMintedFromBarterEvent.InputTuple,
    TSFMintedFromBarterEvent.OutputTuple,
    TSFMintedFromBarterEvent.OutputObject
  >;
  getEvent(
    key: "TSFMintedFromPurchase"
  ): TypedContractEvent<
    TSFMintedFromPurchaseEvent.InputTuple,
    TSFMintedFromPurchaseEvent.OutputTuple,
    TSFMintedFromPurchaseEvent.OutputObject
  >;
  getEvent(
    key: "TaxCollected"
  ): TypedContractEvent<
    TaxCollectedEvent.InputTuple,
    TaxCollectedEvent.OutputTuple,
    TaxCollectedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "UBIClaimed"
  ): TypedContractEvent<
    UBIClaimedEvent.InputTuple,
    UBIClaimedEvent.OutputTuple,
    UBIClaimedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "BarterFacilitatorAuthorized(address)": TypedContractEvent<
      BarterFacilitatorAuthorizedEvent.InputTuple,
      BarterFacilitatorAuthorizedEvent.OutputTuple,
      BarterFacilitatorAuthorizedEvent.OutputObject
    >;
    BarterFacilitatorAuthorized: TypedContractEvent<
      BarterFacilitatorAuthorizedEvent.InputTuple,
      BarterFacilitatorAuthorizedEvent.OutputTuple,
      BarterFacilitatorAuthorizedEvent.OutputObject
    >;

    "BarterFacilitatorRevoked(address)": TypedContractEvent<
      BarterFacilitatorRevokedEvent.InputTuple,
      BarterFacilitatorRevokedEvent.OutputTuple,
      BarterFacilitatorRevokedEvent.OutputObject
    >;
    BarterFacilitatorRevoked: TypedContractEvent<
      BarterFacilitatorRevokedEvent.InputTuple,
      BarterFacilitatorRevokedEvent.OutputTuple,
      BarterFacilitatorRevokedEvent.OutputObject
    >;

    "BusinessAccountCreated(address)": TypedContractEvent<
      BusinessAccountCreatedEvent.InputTuple,
      BusinessAccountCreatedEvent.OutputTuple,
      BusinessAccountCreatedEvent.OutputObject
    >;
    BusinessAccountCreated: TypedContractEvent<
      BusinessAccountCreatedEvent.InputTuple,
      BusinessAccountCreatedEvent.OutputTuple,
      BusinessAccountCreatedEvent.OutputObject
    >;

    "BusinessAuthorized(address)": TypedContractEvent<
      BusinessAuthorizedEvent.InputTuple,
      BusinessAuthorizedEvent.OutputTuple,
      BusinessAuthorizedEvent.OutputObject
    >;
    BusinessAuthorized: TypedContractEvent<
      BusinessAuthorizedEvent.InputTuple,
      BusinessAuthorizedEvent.OutputTuple,
      BusinessAuthorizedEvent.OutputObject
    >;

    "BusinessRevoked(address)": TypedContractEvent<
      BusinessRevokedEvent.InputTuple,
      BusinessRevokedEvent.OutputTuple,
      BusinessRevokedEvent.OutputObject
    >;
    BusinessRevoked: TypedContractEvent<
      BusinessRevokedEvent.InputTuple,
      BusinessRevokedEvent.OutputTuple,
      BusinessRevokedEvent.OutputObject
    >;

    "DemurrageCollected(address,address,uint256,uint256,uint256)": TypedContractEvent<
      DemurrageCollectedEvent.InputTuple,
      DemurrageCollectedEvent.OutputTuple,
      DemurrageCollectedEvent.OutputObject
    >;
    DemurrageCollected: TypedContractEvent<
      DemurrageCollectedEvent.InputTuple,
      DemurrageCollectedEvent.OutputTuple,
      DemurrageCollectedEvent.OutputObject
    >;

    "InactiveRecovered(address,uint256)": TypedContractEvent<
      InactiveRecoveredEvent.InputTuple,
      InactiveRecoveredEvent.OutputTuple,
      InactiveRecoveredEvent.OutputObject
    >;
    InactiveRecovered: TypedContractEvent<
      InactiveRecoveredEvent.InputTuple,
      InactiveRecoveredEvent.OutputTuple,
      InactiveRecoveredEvent.OutputObject
    >;

    "PendingTSFClaimed(address,bytes32,uint256)": TypedContractEvent<
      PendingTSFClaimedEvent.InputTuple,
      PendingTSFClaimedEvent.OutputTuple,
      PendingTSFClaimedEvent.OutputObject
    >;
    PendingTSFClaimed: TypedContractEvent<
      PendingTSFClaimedEvent.InputTuple,
      PendingTSFClaimedEvent.OutputTuple,
      PendingTSFClaimedEvent.OutputObject
    >;

    "PendingTSFCreated(bytes32,uint256)": TypedContractEvent<
      PendingTSFCreatedEvent.InputTuple,
      PendingTSFCreatedEvent.OutputTuple,
      PendingTSFCreatedEvent.OutputObject
    >;
    PendingTSFCreated: TypedContractEvent<
      PendingTSFCreatedEvent.InputTuple,
      PendingTSFCreatedEvent.OutputTuple,
      PendingTSFCreatedEvent.OutputObject
    >;

    "PersonalAccountCreated(address)": TypedContractEvent<
      PersonalAccountCreatedEvent.InputTuple,
      PersonalAccountCreatedEvent.OutputTuple,
      PersonalAccountCreatedEvent.OutputObject
    >;
    PersonalAccountCreated: TypedContractEvent<
      PersonalAccountCreatedEvent.InputTuple,
      PersonalAccountCreatedEvent.OutputTuple,
      PersonalAccountCreatedEvent.OutputObject
    >;

    "PhoneLinked(address,bytes32)": TypedContractEvent<
      PhoneLinkedEvent.InputTuple,
      PhoneLinkedEvent.OutputTuple,
      PhoneLinkedEvent.OutputObject
    >;
    PhoneLinked: TypedContractEvent<
      PhoneLinkedEvent.InputTuple,
      PhoneLinkedEvent.OutputTuple,
      PhoneLinkedEvent.OutputObject
    >;

    "Registered(address,bytes32)": TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
    Registered: TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;

    "TSFMintedFromBarter(bytes32,bytes32,uint256)": TypedContractEvent<
      TSFMintedFromBarterEvent.InputTuple,
      TSFMintedFromBarterEvent.OutputTuple,
      TSFMintedFromBarterEvent.OutputObject
    >;
    TSFMintedFromBarter: TypedContractEvent<
      TSFMintedFromBarterEvent.InputTuple,
      TSFMintedFromBarterEvent.OutputTuple,
      TSFMintedFromBarterEvent.OutputObject
    >;

    "TSFMintedFromPurchase(bytes32,address,uint256,uint256)": TypedContractEvent<
      TSFMintedFromPurchaseEvent.InputTuple,
      TSFMintedFromPurchaseEvent.OutputTuple,
      TSFMintedFromPurchaseEvent.OutputObject
    >;
    TSFMintedFromPurchase: TypedContractEvent<
      TSFMintedFromPurchaseEvent.InputTuple,
      TSFMintedFromPurchaseEvent.OutputTuple,
      TSFMintedFromPurchaseEvent.OutputObject
    >;

    "TaxCollected(uint256)": TypedContractEvent<
      TaxCollectedEvent.InputTuple,
      TaxCollectedEvent.OutputTuple,
      TaxCollectedEvent.OutputObject
    >;
    TaxCollected: TypedContractEvent<
      TaxCollectedEvent.InputTuple,
      TaxCollectedEvent.OutputTuple,
      TaxCollectedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "UBIClaimed(address,uint256)": TypedContractEvent<
      UBIClaimedEvent.InputTuple,
      UBIClaimedEvent.OutputTuple,
      UBIClaimedEvent.OutputObject
    >;
    UBIClaimed: TypedContractEvent<
      UBIClaimedEvent.InputTuple,
      UBIClaimedEvent.OutputTuple,
      UBIClaimedEvent.OutputObject
    >;
  };
}
