/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TesfaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_RATE"
      | "BASIS_POINTS"
      | "DEMURRAGE_RATE_TIER_2"
      | "DEMURRAGE_RATE_TIER_3"
      | "DEMURRAGE_RATE_TIER_4"
      | "DEMURRAGE_RATE_TIER_5"
      | "DEMURRAGE_RATE_TIER_6"
      | "DEMURRAGE_TIER_1_MAX"
      | "DEMURRAGE_TIER_2_MAX"
      | "DEMURRAGE_TIER_3_MAX"
      | "DEMURRAGE_TIER_4_MAX"
      | "DEMURRAGE_TIER_5_MAX"
      | "INACTIVE_THRESHOLD"
      | "INACTIVITY_PERIOD"
      | "MAX_SUPPLY"
      | "PPM"
      | "TAX_RATE"
      | "WEEK"
      | "allowance"
      | "applyDemurrage"
      | "approve"
      | "authorizedCallers"
      | "authorizedFacilitators"
      | "balanceOf"
      | "batchApplyDemurrage"
      | "calculateDemurrage"
      | "claimUBI"
      | "decimals"
      | "distributeUBI"
      | "getAccountInfo"
      | "getClaimableUBI"
      | "getCurrentRate"
      | "getSystemStats"
      | "isBusinessAccount"
      | "isPersonalAccount"
      | "lastActivityTimestamp"
      | "lastDemurrageApplied"
      | "lastDemurrageTimestamp"
      | "lastUBIDistributionTimestamp"
      | "name"
      | "owner"
      | "pause"
      | "paused"
      | "processTransaction"
      | "recordBarter"
      | "recoverInactiveAccount"
      | "registerBusinessAccount"
      | "registerPersonalAccount"
      | "renounceOwnership"
      | "setAuthorizedCaller"
      | "setAuthorizedFacilitator"
      | "symbol"
      | "totalPersonalAccounts"
      | "totalSupply"
      | "totalUBIDistributed"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "ubiClaimed"
      | "ubiPerAccountAccumulated"
      | "ubiPool"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountRegistered"
      | "Approval"
      | "AuthorizedCallerSet"
      | "AuthorizedFacilitatorSet"
      | "BarterRecorded"
      | "DemurrageApplied"
      | "InactiveAccountRecovered"
      | "OwnershipTransferred"
      | "Paused"
      | "TransactionProcessed"
      | "Transfer"
      | "UBIClaimed"
      | "UBIPoolFunded"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BASE_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_RATE_TIER_2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_RATE_TIER_3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_RATE_TIER_4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_RATE_TIER_5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_RATE_TIER_6",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_TIER_1_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_TIER_2_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_TIER_3_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_TIER_4_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEMURRAGE_TIER_5_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INACTIVE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INACTIVITY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PPM", values?: undefined): string;
  encodeFunctionData(functionFragment: "TAX_RATE", values?: undefined): string;
  encodeFunctionData(functionFragment: "WEEK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyDemurrage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedFacilitators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchApplyDemurrage",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDemurrage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claimUBI", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "distributeUBI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableUBI",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSystemStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBusinessAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPersonalAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastActivityTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDemurrageApplied",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDemurrageTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastUBIDistributionTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processTransaction",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordBarter",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverInactiveAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBusinessAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPersonalAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedFacilitator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalPersonalAccounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUBIDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ubiClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ubiPerAccountAccumulated",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ubiPool", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BASE_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_RATE_TIER_2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_RATE_TIER_3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_RATE_TIER_4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_RATE_TIER_5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_RATE_TIER_6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_TIER_1_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_TIER_2_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_TIER_3_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_TIER_4_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEMURRAGE_TIER_5_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INACTIVE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INACTIVITY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PPM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TAX_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WEEK", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "applyDemurrage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedFacilitators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchApplyDemurrage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDemurrage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimUBI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeUBI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableUBI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSystemStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBusinessAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPersonalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastActivityTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDemurrageApplied",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDemurrageTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUBIDistributionTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordBarter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverInactiveAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBusinessAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPersonalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPersonalAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUBIDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ubiClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ubiPerAccountAccumulated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ubiPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AccountRegisteredEvent {
  export type InputTuple = [
    account: AddressLike,
    isPersonal: boolean,
    isBusiness: boolean
  ];
  export type OutputTuple = [
    account: string,
    isPersonal: boolean,
    isBusiness: boolean
  ];
  export interface OutputObject {
    account: string;
    isPersonal: boolean;
    isBusiness: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizedCallerSetEvent {
  export type InputTuple = [caller: AddressLike, authorized: boolean];
  export type OutputTuple = [caller: string, authorized: boolean];
  export interface OutputObject {
    caller: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizedFacilitatorSetEvent {
  export type InputTuple = [facilitator: AddressLike, authorized: boolean];
  export type OutputTuple = [facilitator: string, authorized: boolean];
  export interface OutputObject {
    facilitator: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BarterRecordedEvent {
  export type InputTuple = [
    party1: AddressLike,
    party2: AddressLike,
    estimatedValue: BigNumberish,
    facilitator: AddressLike,
    party1Minted: BigNumberish,
    party2Minted: BigNumberish,
    taxCollected: BigNumberish
  ];
  export type OutputTuple = [
    party1: string,
    party2: string,
    estimatedValue: bigint,
    facilitator: string,
    party1Minted: bigint,
    party2Minted: bigint,
    taxCollected: bigint
  ];
  export interface OutputObject {
    party1: string;
    party2: string;
    estimatedValue: bigint;
    facilitator: string;
    party1Minted: bigint;
    party2Minted: bigint;
    taxCollected: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DemurrageAppliedEvent {
  export type InputTuple = [
    account: AddressLike,
    amount: BigNumberish,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    amount: bigint,
    newBalance: bigint
  ];
  export interface OutputObject {
    account: string;
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InactiveAccountRecoveredEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionProcessedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    seller: AddressLike,
    paymentAmount: BigNumberish,
    buyerMinted: BigNumberish,
    sellerMinted: BigNumberish,
    taxCollected: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    seller: string,
    paymentAmount: bigint,
    buyerMinted: bigint,
    sellerMinted: bigint,
    taxCollected: bigint
  ];
  export interface OutputObject {
    buyer: string;
    seller: string;
    paymentAmount: bigint;
    buyerMinted: bigint;
    sellerMinted: bigint;
    taxCollected: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UBIClaimedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UBIPoolFundedEvent {
  export type InputTuple = [amount: BigNumberish, source: string];
  export type OutputTuple = [amount: bigint, source: string];
  export interface OutputObject {
    amount: bigint;
    source: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tesfa extends BaseContract {
  connect(runner?: ContractRunner | null): Tesfa;
  waitForDeployment(): Promise<this>;

  interface: TesfaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_RATE: TypedContractMethod<[], [bigint], "view">;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_RATE_TIER_2: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_RATE_TIER_3: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_RATE_TIER_4: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_RATE_TIER_5: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_RATE_TIER_6: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_TIER_1_MAX: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_TIER_2_MAX: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_TIER_3_MAX: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_TIER_4_MAX: TypedContractMethod<[], [bigint], "view">;

  DEMURRAGE_TIER_5_MAX: TypedContractMethod<[], [bigint], "view">;

  INACTIVE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  INACTIVITY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  PPM: TypedContractMethod<[], [bigint], "view">;

  TAX_RATE: TypedContractMethod<[], [bigint], "view">;

  WEEK: TypedContractMethod<[], [bigint], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  applyDemurrage: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  authorizedFacilitators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  batchApplyDemurrage: TypedContractMethod<
    [accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  calculateDemurrage: TypedContractMethod<
    [balance: BigNumberish],
    [bigint],
    "view"
  >;

  claimUBI: TypedContractMethod<[], [void], "nonpayable">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  distributeUBI: TypedContractMethod<[], [void], "nonpayable">;

  getAccountInfo: TypedContractMethod<
    [account: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        personal: boolean;
        business: boolean;
        balance: bigint;
        lastActivity: bigint;
        pendingDemurrage: bigint;
        claimableUBI: bigint;
      }
    ],
    "view"
  >;

  getClaimableUBI: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getCurrentRate: TypedContractMethod<[], [bigint], "view">;

  getSystemStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        currentSupply: bigint;
        maxSupply: bigint;
        currentRate: bigint;
        poolBalance: bigint;
        personalAccounts: bigint;
        distributedUBI: bigint;
      }
    ],
    "view"
  >;

  isBusinessAccount: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isPersonalAccount: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  lastActivityTimestamp: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  lastDemurrageApplied: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  lastDemurrageTimestamp: TypedContractMethod<[], [bigint], "view">;

  lastUBIDistributionTimestamp: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processTransaction: TypedContractMethod<
    [buyer: AddressLike, seller: AddressLike, paymentAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordBarter: TypedContractMethod<
    [
      party1: AddressLike,
      party2: AddressLike,
      estimatedValue: BigNumberish,
      facilitator: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  recoverInactiveAccount: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  registerBusinessAccount: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  registerPersonalAccount: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setAuthorizedFacilitator: TypedContractMethod<
    [facilitator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalPersonalAccounts: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  totalUBIDistributed: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  ubiClaimed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  ubiPerAccountAccumulated: TypedContractMethod<[], [bigint], "view">;

  ubiPool: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_RATE_TIER_2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_RATE_TIER_3"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_RATE_TIER_4"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_RATE_TIER_5"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_RATE_TIER_6"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_TIER_1_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_TIER_2_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_TIER_3_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_TIER_4_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEMURRAGE_TIER_5_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INACTIVE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INACTIVITY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PPM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TAX_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WEEK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "applyDemurrage"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizedFacilitators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchApplyDemurrage"
  ): TypedContractMethod<[accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateDemurrage"
  ): TypedContractMethod<[balance: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimUBI"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributeUBI"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccountInfo"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        personal: boolean;
        business: boolean;
        balance: bigint;
        lastActivity: bigint;
        pendingDemurrage: bigint;
        claimableUBI: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimableUBI"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSystemStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        currentSupply: bigint;
        maxSupply: bigint;
        currentRate: bigint;
        poolBalance: bigint;
        personalAccounts: bigint;
        distributedUBI: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBusinessAccount"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPersonalAccount"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastActivityTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastDemurrageApplied"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastDemurrageTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastUBIDistributionTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processTransaction"
  ): TypedContractMethod<
    [buyer: AddressLike, seller: AddressLike, paymentAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordBarter"
  ): TypedContractMethod<
    [
      party1: AddressLike,
      party2: AddressLike,
      estimatedValue: BigNumberish,
      facilitator: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoverInactiveAccount"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerBusinessAccount"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerPersonalAccount"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedFacilitator"
  ): TypedContractMethod<
    [facilitator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalPersonalAccounts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUBIDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ubiClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "ubiPerAccountAccumulated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ubiPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AccountRegistered"
  ): TypedContractEvent<
    AccountRegisteredEvent.InputTuple,
    AccountRegisteredEvent.OutputTuple,
    AccountRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizedCallerSet"
  ): TypedContractEvent<
    AuthorizedCallerSetEvent.InputTuple,
    AuthorizedCallerSetEvent.OutputTuple,
    AuthorizedCallerSetEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizedFacilitatorSet"
  ): TypedContractEvent<
    AuthorizedFacilitatorSetEvent.InputTuple,
    AuthorizedFacilitatorSetEvent.OutputTuple,
    AuthorizedFacilitatorSetEvent.OutputObject
  >;
  getEvent(
    key: "BarterRecorded"
  ): TypedContractEvent<
    BarterRecordedEvent.InputTuple,
    BarterRecordedEvent.OutputTuple,
    BarterRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DemurrageApplied"
  ): TypedContractEvent<
    DemurrageAppliedEvent.InputTuple,
    DemurrageAppliedEvent.OutputTuple,
    DemurrageAppliedEvent.OutputObject
  >;
  getEvent(
    key: "InactiveAccountRecovered"
  ): TypedContractEvent<
    InactiveAccountRecoveredEvent.InputTuple,
    InactiveAccountRecoveredEvent.OutputTuple,
    InactiveAccountRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionProcessed"
  ): TypedContractEvent<
    TransactionProcessedEvent.InputTuple,
    TransactionProcessedEvent.OutputTuple,
    TransactionProcessedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "UBIClaimed"
  ): TypedContractEvent<
    UBIClaimedEvent.InputTuple,
    UBIClaimedEvent.OutputTuple,
    UBIClaimedEvent.OutputObject
  >;
  getEvent(
    key: "UBIPoolFunded"
  ): TypedContractEvent<
    UBIPoolFundedEvent.InputTuple,
    UBIPoolFundedEvent.OutputTuple,
    UBIPoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AccountRegistered(address,bool,bool)": TypedContractEvent<
      AccountRegisteredEvent.InputTuple,
      AccountRegisteredEvent.OutputTuple,
      AccountRegisteredEvent.OutputObject
    >;
    AccountRegistered: TypedContractEvent<
      AccountRegisteredEvent.InputTuple,
      AccountRegisteredEvent.OutputTuple,
      AccountRegisteredEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "AuthorizedCallerSet(address,bool)": TypedContractEvent<
      AuthorizedCallerSetEvent.InputTuple,
      AuthorizedCallerSetEvent.OutputTuple,
      AuthorizedCallerSetEvent.OutputObject
    >;
    AuthorizedCallerSet: TypedContractEvent<
      AuthorizedCallerSetEvent.InputTuple,
      AuthorizedCallerSetEvent.OutputTuple,
      AuthorizedCallerSetEvent.OutputObject
    >;

    "AuthorizedFacilitatorSet(address,bool)": TypedContractEvent<
      AuthorizedFacilitatorSetEvent.InputTuple,
      AuthorizedFacilitatorSetEvent.OutputTuple,
      AuthorizedFacilitatorSetEvent.OutputObject
    >;
    AuthorizedFacilitatorSet: TypedContractEvent<
      AuthorizedFacilitatorSetEvent.InputTuple,
      AuthorizedFacilitatorSetEvent.OutputTuple,
      AuthorizedFacilitatorSetEvent.OutputObject
    >;

    "BarterRecorded(address,address,uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      BarterRecordedEvent.InputTuple,
      BarterRecordedEvent.OutputTuple,
      BarterRecordedEvent.OutputObject
    >;
    BarterRecorded: TypedContractEvent<
      BarterRecordedEvent.InputTuple,
      BarterRecordedEvent.OutputTuple,
      BarterRecordedEvent.OutputObject
    >;

    "DemurrageApplied(address,uint256,uint256)": TypedContractEvent<
      DemurrageAppliedEvent.InputTuple,
      DemurrageAppliedEvent.OutputTuple,
      DemurrageAppliedEvent.OutputObject
    >;
    DemurrageApplied: TypedContractEvent<
      DemurrageAppliedEvent.InputTuple,
      DemurrageAppliedEvent.OutputTuple,
      DemurrageAppliedEvent.OutputObject
    >;

    "InactiveAccountRecovered(address,uint256)": TypedContractEvent<
      InactiveAccountRecoveredEvent.InputTuple,
      InactiveAccountRecoveredEvent.OutputTuple,
      InactiveAccountRecoveredEvent.OutputObject
    >;
    InactiveAccountRecovered: TypedContractEvent<
      InactiveAccountRecoveredEvent.InputTuple,
      InactiveAccountRecoveredEvent.OutputTuple,
      InactiveAccountRecoveredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TransactionProcessed(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TransactionProcessedEvent.InputTuple,
      TransactionProcessedEvent.OutputTuple,
      TransactionProcessedEvent.OutputObject
    >;
    TransactionProcessed: TypedContractEvent<
      TransactionProcessedEvent.InputTuple,
      TransactionProcessedEvent.OutputTuple,
      TransactionProcessedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "UBIClaimed(address,uint256)": TypedContractEvent<
      UBIClaimedEvent.InputTuple,
      UBIClaimedEvent.OutputTuple,
      UBIClaimedEvent.OutputObject
    >;
    UBIClaimed: TypedContractEvent<
      UBIClaimedEvent.InputTuple,
      UBIClaimedEvent.OutputTuple,
      UBIClaimedEvent.OutputObject
    >;

    "UBIPoolFunded(uint256,string)": TypedContractEvent<
      UBIPoolFundedEvent.InputTuple,
      UBIPoolFundedEvent.OutputTuple,
      UBIPoolFundedEvent.OutputObject
    >;
    UBIPoolFunded: TypedContractEvent<
      UBIPoolFundedEvent.InputTuple,
      UBIPoolFundedEvent.OutputTuple,
      UBIPoolFundedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
