// Auto-generated by deployment script
// Network: Polygon Amoy Testnet (Chain ID: 80002)
// Deployed: 2026-04-21

export const TESFA_CONTRACT_ADDRESS = "0xc92503d6405954ef5388fBE1E3a3288498Cc482F";
export const DEPLOYMENT_TX_HASH = "0xd5b03cb0f9d964aab182954e106fcb1236fa3871f269043801a632f187c6dc10";
export const DEPLOYER_ADDRESS = "0xc5235ec1b24309033C4cE68F5031BdeB1003612B";
export const NETWORK = {
  name: "Polygon Amoy Testnet",
  chainId: 80002,
  rpc: "https://rpc-amoy.polygon.technology/",
  explorer: "https://amoy.polygonscan.com/"
};
